<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="title" content="US Domagné Saint-Didier" />
        <meta name="description" content="Site officiel de l'US Domagné Saint-Didier" />
        <meta name="keywords" content="domagné,usd,foot,football,site" />
        <meta name="author" content="Dendeey" />
        <meta name="referrer" content="origin" />
        <meta property="og:title" content="Site officiel de l'US Domagné Saint-Didier" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="https://davidsim.sites.3wa.io/projectP/usdomagne/usd.html" />
        <meta property="og:image" content="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" />
        <meta property="og:description" content="Site officiel de l'US Domagné Saint-Didier !" />
        <meta property="og:locale" content="fr_FR" />
        <meta property="og:site_name" content="US Domagné Saint-Didier" />
        
        <link rel="shortcut icon" href="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" type="image/x-icon">
        <link rel="stylesheet" href="assets/styles/css/style.css"/>
        
        <script src="https://kit.fontawesome.com/2a74f636e2.js" crossorigin="anonymous"></script>
        
        <title>Espace Administrateur</title>
    </head>
    <body>
        <?php require 'partials/_adminHeader.phtml'; ?>
        
        <main>
        
        <?php require  $template."/".$template.".phtml"; ?>
        
        </main>
        
        <?php // require 'partials/_adminFooter.phtml'; ?>
    </body>
</html>