<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="title" content="US Domagné Saint-Didier" />
        <meta name="description" content="Site officiel de l'US Domagné Saint-Didier" />
        <meta name="keywords" content="domagné,usd,foot,football,site" />
        <meta name="author" content="Dendeey" />
        <meta name="referrer" content="origin" />
        <meta property="og:title" content="Site officiel de l'US Domagné Saint-Didier" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="https://davidsim.sites.3wa.io/projectP/usdomagne/usd.html" />
        <meta property="og:image" content="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" />
        <meta property="og:description" content="Site officiel de l'US Domagné Saint-Didier !" />
        <meta property="og:locale" content="fr_FR" />
        <meta property="og:site_name" content="US Domagné Saint-Didier" />
        
        <link rel="shortcut icon" href="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" type="image/x-icon">
        <link rel="stylesheet" href="/res03-projet-final/usdomagne/assets/styles/css/style.css"/>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;800&display=swap" rel="stylesheet">

        <script src="https://kit.fontawesome.com/2a74f636e2.js" crossorigin="anonymous"></script>
        
        <title>Union Sportive Domagné Saint-Didier</title>
    </head>
    <body id="public-layout">
        <?php require 'partials/header.phtml'; ?>
        
        <?php require $template.".phtml"; ?>
        
        <?php require 'partials/footer.phtml'; ?>
        <script type="module" src="/res03-projet-final/usdomagne/assets/js/index.js"></script>
    </body>
</html>