<main>
    <aside>
        <h1>Menu</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne/admin/convocations">Convocations</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/joueurs">Joueurs</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/arbitres">Arbitres</a></li>
                <li><a href="">Bureau</a></li>
                <li><a href="">Staff</a></li>
                <li><a href="">Articles</a></li>
                <li><a href="">Admins</a></li>
            </ul>
        </nav>
    </aside>
</main>