<main id="admin-aside">
    <aside>
        <h1>Menu</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne/admin/joueurs">Joueurs</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/convocations">Convocations</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/arbitres">Arbitres</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/bureau">Bureau</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/staff">Staff</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/articles">Articles</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/media">Media</a></li>
                <li><a href="/res03-projet-final/usdomagne/admin/admins">Admins</a></li>
            </ul>
        </nav>
    </aside>
</main>