<main id="contact">
    <header>
        <h1>Contact</h1>
    </header>
    <section>
        <section>
            <form method="post" action="">
                <h2>Nous contacter</h2>
                <fieldset>
                    <label for="contact-lastname"></label>
                    <input type="text" name="contact-lastname" placeholder="Votre nom">
                    <label for="contact-firstname"></label>
                    <input type="text" name="contact-firstname" placeholder="Votre prénom">
                </fieldset>
                <fieldset>
                    <label for="contact-email"></label>
                    <input type="email" name="contact-email" placeholder="Votre email">
                </fieldset>
                <fieldset>
                    <label for="contact-objet"></label>
                    <input type="text" name="contact-objet" placeholder="Objet">
                </fieldset>
                <fieldset>
                    <label for="contact-message"></label>
                    <textarea name="contact-message" rows="10" cols="66" placeholder="Message"></textarea>
                </fieldset>
                <fieldset>
                    <input type="submit" class="contact-submit" value="Envoyer">
                </fieldset>
            </form>
            <section>
                <h2>Coordonnées du club</h2>
                <ul>
                    <li><span class="fa-solid fa-location-dot fa-xl"></span>Mairie de Domagné, 8 Allée Saint Pierre,<br>35113 Domagné</li>
                    <li><span class="fa-solid fa-phone fa-xl"></span>02 99 00 04 24</li>
                    <li><span class="fa-solid fa-envelope fa-xl"></span>admin@admin.fr</li>
                </ul>
            </section>
        </section>
    </section>
</main>