<form action="/res03-projet-final/usdomagne/admin/joueurs/creer-un-joueur" method="post">
    <fieldset>
        <label for="add-firstname">Prénom</label>
        <input type="text" name="add-firstname"/>
    </fieldset>
    <fieldset>
        <label for="add-lastname">Nom</label>
        <input type="text" name="add-lastname"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer" id="addPlayer-button" />
    </fieldset>
    <input type="hidden" name="formAddPlayer"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/joueurs">Retour aux joueurs</a></button>