<main>
    <section>
        <h1>Créer un joueur :</h1>
        <form action="/usdomagne/usdomagne/admin/joueurs/creer-un-joueur" method="post">
            <fieldset class="mb-3">
                <label for="add-firstname" class="form-label">Prénom</label>
                <input type="text" class="form-control" name="add-firstname"/>
            </fieldset>
            <fieldset class="mb-3">
                <label for="add-lastname" class="form-label">Nom</label>
                <input type="text" class="form-control" name="add-lastname"/>
            </fieldset>
            <fieldset class="submit">
                <input type="submit" class="btn btn-primary" name="submit" value="Enregistrer"/>
            </fieldset>
            <input type="hidden" name="formAddPlayer"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/usdomagne/usdomagne/admin/joueurs" class="btn btn-warning">Retour aux joueurs</a></button>
    </section>
</main>
