<form action="creer-un-joueur" method="post">
    <fieldset>
        <label for="add-firstname">Prénom</label>
        <input type="text" name="add-firstname"/>
    </fieldset>
    <fieldset>
        <label for="add-lastname">Nom</label>
        <input type="text" name="add-lastname"/>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer" id="addPlayer-button" />
    </fieldset>
    <input type="hidden" name="formAddPlayer"/>
</form>