<main>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data['players'] as $player){ ?>
            
            <tr>
                <td><?php echo $player->getId(); ?></td>
                <td><?php echo $player->getFirstName(); ?></td>
                <td><?php echo $player->getLastName(); ?></td>
                <td class="actions">
                    <a href="/res03-projet-final/usdomagne/admin/joueurs/modifier/<?= $player->getId(); ?>"><span class="fa-solid fa-pen-to-square fa-lg" style="color: green;"></span></a>
                    <a href="/res03-projet-final/usdomagne/admin/joueurs/supprimer/<?= $player->getId(); ?>"><span class="fa-solid fa-trash fa-lg" style="color: red;"></span></a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <section class="section-btn">
        <button><a href="/res03-projet-final/usdomagne/admin/joueurs/creer-un-joueur" class="btn btn-warning">Ajouter un joueur</a></button>
        <button><a href="/res03-projet-final/usdomagne/admin" class="btn btn-warning">Retour au menu</a></button>
    </section>
</main>