<form action="/res03-projet-final/usdomagne/admin/joueurs/modifier" method="post">
    <fieldset>
        <label for="edit-firstname">Prénom</label>
        <input type="text" name="edit-firstname">
    </fieldset>
    <fieldset>
        <label for="edit-lastname">Nom</label>
        <input type="text" name="edit-lastname">
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer"/>
    </fieldset>
    <input type="hidden" name="formEditPlayer"/>
</form>