<table>
    <tbody>
        <tr>
            <th>Id</th>
            <td></td>
        </tr>
        <tr>
            <th>Prénom</th>
            <td></td>
        </tr>
        <tr>
            <th>Nom</th>
            <td></td>
        </tr>
    </tbody>
</table>

<h1><a href="/res03-projet-final/usdomagne/admin/joueurs">Retour au joueurs</a></h1>
<h2><a href="/res03-projet-final/usdomagne/admin/joueurs/modifier">Modifier</a></h2>