<main id="arbitres">
    <header>
        <h1>Arbitrage</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Arbitrage</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach($data['pageArbitrage'] as $arbitre){ ?> 
            <article>
                <figure>
                    <img src="/res03-projet-final/usdomagne/<?= $arbitre->getMedias()[0]->getUrl(); ?>" alt="Image de l'actualité">
                </figure>
                <section>
                    <h2><?= $arbitre->getFirstName(); ?><span> </span><?= $arbitre->getlastName(); ?></h2>
                </section>
            </article>
            <?php } ?>
        </section>
    </section>
</main>