<main id="arbitres">
    <header>
        <h1>Arbitrage</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Arbitrage</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach ($data['pageArbitrage'] as $arbitre) { ?>

                <figure>
                    <img src="/usdomagne/usdomagne/<?= $arbitre->getMedias()[0]->getUrl(); ?>" alt="Image de l'arbitre">
                </figure>
                <!-- <section>
                    <h2><?= $arbitre->getFirstName(); ?><span> </span><?= $arbitre->getlastName(); ?></h2>
                </section> -->

            <?php } ?>
        </section>
    </section>
</main>