<main>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Téléphone portable</th>
                <th>Fonction</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data['staffs'] as $office){ ?>
            
            <tr>
                <td><?php echo $office->getId(); ?></td>
                <td><?php echo $office->getFirstName(); ?></td>
                <td><?php echo $office->getLastName(); ?></td>
                <td><?php echo $office->getPhoneNumber(); ?></td>
                <td><?php echo $office->getRole(); ?></td>
                <td class="actions">
                    <a href="/usdomagne/usdomagne/admin/staff/voir/<?= $office->getId(); ?>"><span class="fa-solid fa-eye fa-lg"></span></a>
                    <a href="/usdomagne/usdomagne/admin/staff/modifier/<?= $office->getId(); ?>"><span class="fa-solid fa-pen-to-square fa-lg" style="color: green;"></span></a>
                    <a href="/usdomagne/usdomagne/admin/staff/supprimer/<?= $office->getId(); ?>"><span class="fa-solid fa-trash fa-lg" style="color: red;"></span></a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <section class="section-btn" >
        <button><a href="/usdomagne/usdomagne/admin/staff/creer-un-staff" class="btn btn-warning">Ajouter un staff</a></button>
        <button><a href="/usdomagne/usdomagne/admin" class="btn btn-warning">Retour au menu</a></button>
    </section>
</main>