<main>
    <section>
        <h1>Modifier ce staff :</h1>
        <form action="/usdomagne/usdomagne/admin/staff/modifier/<?php echo($data['staff']->getId()); ?>" method="post">
            <fieldset class="mb-3">
                <label for="edit-firstname">Prénom</label>
                <input type="text" class="form-control" name="edit-firstname" value="<?= $data['staff']->getFirstName(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-lastname">Nom</label>
                <input type="text" class="form-control" name="edit-lastname" value="<?= $data['staff']->getLastName(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-phonenumber">Télephone portable</label>
                <input type="text" class="form-control" name="edit-phonenumber" value="<?= $data['staff']->getPhoneNumber(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-role">Fonction</label>
                <input type="text" class="form-control" name="edit-role" value="<?= $data['staff']->getRole(); ?>">
            </fieldset>
            <fieldset class="submit">
                <input type="submit" name="submit" value="Enregistrer" class="btn btn-primary"/>
            </fieldset>
            <input type="hidden" name="formEditStaff"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/usdomagne/usdomagne/admin/staff" class="btn btn-warning">Retour au staff</a></button>
    </section>
</main>
