<form action="/res03-projet-final/usdomagne/admin/staff/modifier/<?php echo($data['staff']->getId()); ?>" method="post">
    <fieldset>
        <label for="edit-firstname">Prénom</label>
        <input type="text" name="edit-firstname" value="<?= $data['staff']->getFirstName(); ?>">
    </fieldset>
    <fieldset>
        <label for="edit-lastname">Nom</label>
        <input type="text" name="edit-lastname" value="<?= $data['staff']->getLastName(); ?>">
    </fieldset>
    <fieldset>
        <label for="edit-phonenumber">Télephone portable</label>
        <input type="text" name="edit-phonenumber" value="<?= $data['staff']->getPhoneNumber(); ?>">
    </fieldset>
    <fieldset>
        <label for="edit-role">Fonction</label>
        <input type="text" name="edit-role" value="<?= $data['staff']->getRole(); ?>">
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer"/>
    </fieldset>
    <input type="hidden" name="formEditStaff"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/staff">Retour au staff</a></button>