<form>
    <fieldset>
        <label for="show-firstname">Prénom</label>
        <input type="text" name="show-firstname" value="<?= $data['staff']->getFirstName(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <label for="show-lastname">Nom</label>
        <input type="text" name="show-lastname" value="<?= $data['staff']->getLastName(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <label for="show-phonenumber">Nom</label>
        <input type="text" name="show-phonenumber" value="<?= $data['staff']->getPhoneNumber(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <label for="show-role">Nom</label>
        <input type="text" name="show-role" value="<?= $data['staff']->getRole(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <figure>
            <img src="/res03-projet-final/usdomagne/<?= $data['staff']->getMedias()[0]->getUrl(); ?>">
        </figure>
    </fieldset>
    <input type="hidden" name="formShowStaff"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/staff">Retour au staff</a></button>