<main>
    <section>
        <h1>Créer un bureau :</h1>
        <form action="/usdomagne/usdomagne/admin/bureau/creer-un-bureau" method="post" enctype="multipart/form-data">
            <fieldset class="mb-3">
                <label for="add-firstname">Prénom</label>
                <input type="text" class="form-control" name="add-firstname"/>
            </fieldset>
            <fieldset class="mb-3">
                <label for="add-lastname">Nom</label>
                <input type="text" class="form-control" name="add-lastname"/>
            </fieldset>
            <fieldset class="mb-3">
                <label for="add-phonenumber">Téléphone portable</label>
                <input type="text" class="form-control" name="add-phonenumber"/>
            </fieldset>
            <fieldset class="mb-3">
                <label for="add-role">Fonction</label>
                <input type="text" class="form-control" name="add-role"/>
            </fieldset>
            <fieldset class="mb-3">
                <label for="add-image">Image</label>
                <input type="file" class="form-control" name="add-image"/>
            </fieldset>
            <fieldset class="submit">
                <input type="submit" name="submit" value="Enregistrer" class="btn btn-primary"/>
            </fieldset>
            <input type="hidden" name="formAddOffice"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/usdomagne/usdomagne/admin/bureau" class="btn btn-warning">Retour au bureau</a></button>
    </section>
</main>