<form action="/res03-projet-final/usdomagne/admin/bureau/creer-un-bureau" method="post" enctype="multipart/form-data">
    <fieldset>
        <label for="add-firstname">Prénom</label>
        <input type="text" name="add-firstname"/>
    </fieldset>
    <fieldset>
        <label for="add-lastname">Nom</label>
        <input type="text" name="add-lastname"/>
    </fieldset>
    <fieldset>
        <label for="add-phonenumber">Téléphone portable</label>
        <input type="text" name="add-phonenumber"/>
    </fieldset>
    <fieldset>
        <label for="add-role">Fonction</label>
        <input type="text" name="add-role"/>
    </fieldset>
    <fieldset>
        <label for="add-image">Image</label>
        <input type="file" name="add-image"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer" />
    </fieldset>
    <input type="hidden" name="formAddOffice"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/bureau">Retour au bureau</a></button>