<main>
    <section>
        <h1>Modifier ce bureau :</h1>
        <form action="/res03-projet-final/usdomagne/admin/bureau/modifier/<?php echo($data['office']->getId()); ?>" method="post">
            <fieldset class="mb-3">
                <label for="edit-firstname">Prénom</label>
                <input type="text" class="form-control"  name="edit-firstname" value="<?= $data['office']->getFirstName(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-lastname">Nom</label>
                <input type="text" class="form-control" name="edit-lastname" value="<?= $data['office']->getLastName(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-phonenumber">Télephone portable</label>
                <input type="text" class="form-control" name="edit-phonenumber" value="<?= $data['office']->getPhoneNumber(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-role">Fonction</label>
                <input type="text" class="form-control" name="edit-role" value="<?= $data['office']->getRole(); ?>">
            </fieldset>
            <fieldset class="submit">
                <input type="submit" name="submit" value="Enregistrer" class="btn btn-primary"/>
            </fieldset>
            <input type="hidden" name="formEditOffice"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/res03-projet-final/usdomagne/admin/bureau" class="btn btn-warning">Retour au bureau</a></button>
    </section>
</main>