<main id="equipes">
    <header>
        <h1>Séniors</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Séniors</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <a href="/res03-projet-final/usdomagne/seniors/a">
                <article>
                    <header>
                        <h1>Sénior A</h1>
                    </header>
                    <figure>
                        <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/teams/seniors-a4__rtrhxt.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="/res03-projet-final/usdomagne/seniors/b">
                <article>
                    <header>
                        <h1>Sénior B</h1>
                    </header>
                    <figure>
                        <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/teams/seniors-a4__rtrhxt.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="/res03-projet-final/usdomagne/seniors/c">
                <article>
                    <header>
                        <h1>Sénior C</h1>
                    </header>
                    <figure>
                        <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/teams/seniors-a4__rtrhxt.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
        </section>
    </section>
</main>