<main id="equipes">
    <header>
        <h1>Vétérans</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Vétérans</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <a href="#">
                <article>
                    <header>
                        <h1>Vétérans</h1>
                    </header>
                    <figure>
                        <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/teams/seniors-a4__rtrhxt.jpg">
                    </figure>
                </article>
            </a>
        </section>
    </section>
</main>