<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($data['referees'] as $referee){ ?>
        
        <tr>
            <td><?php echo $referee->getId(); ?></td>
            <td><?php echo $referee->getFirstName(); ?></td>
            <td><?php echo $referee->getLastName(); ?></td>
            <td><?php echo $referee->getImage(); ?></td>
            <td>
                <a href="/res03-projet-final/usdomagne/admin/arbitres/modifier/<?= $referee->getId(); ?>">Modifier</a>
                <a href="/res03-projet-final/usdomagne/admin/arbitres/supprimer/<?= $referee->getId(); ?>">Supprimer</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<button><a href="/res03-projet-final/usdomagne/admin/arbitres/creer-un-arbitre">Ajouter un arbitre</a></button>
<button><a href="/res03-projet-final/usdomagne/admin">Retour au menu</a></button>