<main>
    <section>
        <h1>Modifier cet arbitre :</h1>
        <form action="/res03-projet-final/usdomagne/admin/arbitres/modifier/<?php echo($data['referees']->getId()); ?>" method="post">
            <fieldset class="mb-3">
                <label for="edit-firstname" class="form-label">Prénom</label>
                <input type="text" class="form-control" name="edit-firstname" value="<?= $data['referees']->getFirstName(); ?>">
            </fieldset>
            <fieldset class="mb-3">
                <label for="edit-lastname" class="form-label">Nom</label>
                <input type="text" class="form-control" name="edit-lastname" value="<?= $data['referees']->getLastName(); ?>">
            </fieldset>
            <fieldset class="submit">
                <input type="submit" name="submit" value="Enregistrer" class="btn btn-primary"/>
            </fieldset>
            <input type="hidden" name="formEditReferee"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/res03-projet-final/usdomagne/admin/arbitres" class="btn btn-warning">Retour aux arbitres</a></button>
    </section>
</main>