<form>
    <fieldset>
        <label for="show-firstname">Prénom</label>
        <input type="text" name="show-firstname" value="<?= $data['referees']->getFirstName(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <label for="show-lastname">Nom</label>
        <input type="text" name="show-lastname" value="<?= $data['referees']->getLastName(); ?>" disabled="disabled">
    </fieldset>
    <fieldset>
        <figure>
            <img src="/res03-projet-final/usdomagne/<?= $data['referees']->getMedias()[0]->getUrl(); ?>">
        </figure>
    </fieldset>
    <input type="hidden" name="formShowReferee"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/arbitres">Retour aux arbitres</a></button>