<main>
    <section>
        <h1>Voir cet arbitre :</h1>
        <!-- <?= var_dump($data['referees']); ?> -->
        <form>
            <fieldset class="form-floating mb-3">
                <label for="show-firstname">Prénom</label>
                <input type="text" class="form-control" name="show-firstname"  value="<?= $data['referees']->getFirstName(); ?>" disabled="disabled">
            </fieldset>
            <fieldset class="form-floating mb-3">
                <label for="show-lastname">Nom</label>
                <input type="text" class="form-control" name="show-lastname" value="<?= $data['referees']->getLastName(); ?>" disabled="disabled">
            </fieldset>
            <fieldset class="form-floating mb-3">
                <figure>
                    <img src="/usdomagne/usdomagne/<?= $data['referees']->getMedias()[0]->getUrl(); ?>" alt="Image de l'arbitre côté admin">
                </figure>
            </fieldset>
            <input type="hidden" name="formShowReferee"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/usdomagne/usdomagne/admin/arbitres" class="btn btn-warning">Retour aux arbitres</a></button>
    </section>
</main>