<main id="equipe-id-card">
    <header>
        <h1>Sénior B</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li><a href="/usdomagne/usdomagne/seniors">Séniors</a></li>
                <li><span>/</span></li>
                <li>Sénior B</li>
            </ul>
        </nav>
    </header>
    <section>
        <section id="img-schedule">
            <figure>
                <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/teams/seniors-a4__rtrhxt.jpg" alt="Image de l'équipe">
                <h2>District 3</h2>
            </figure>
            <article>
                <header>
                    <h3>Résultats</h3>
                    <span>&</span>
                    <h3>Calendrier</h3>
                </header>
                <iframe id="644b92c05f131e08cdf2e5a5" height="400" src="https://v1.scorenco.com/widget/644b92c05f131e08cdf2e5a5/" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;"></iframe>
            </article>
        </section>
        <section id="next-game">
            <header>
                <h3>L'actualité des séniors B</h3>
            </header>
            <article>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
                <script>
                    if (!window._rsz) {
                        window._rsz = function() {
                            var i = iFrameResize({
                                checkOrigin: false,
                                interval: 100
                            });
                        };
                        if (document.readyState != "loading") {
                            _rsz()
                        } else {
                            document.addEventListener("DOMContentLoaded", _rsz)
                        }
                    }
                </script><iframe id="644b99b65f131e08cfd5471c" src="https://v1.scorenco.com/widget/644b99b65f131e08cfd5471c/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
            </article>
            <article>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
                <script>
                    if (!window._rsz) {
                        window._rsz = function() {
                            var i = iFrameResize({
                                checkOrigin: false,
                                interval: 100
                            });
                        };
                        if (document.readyState != "loading") {
                            _rsz()
                        } else {
                            document.addEventListener("DOMContentLoaded", _rsz)
                        }
                    }
                </script><iframe id="644b9e595f131e08d3433892" src="https://v1.scorenco.com/widget/644b9e595f131e08d3433892/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
            </article>
        </section>
    </section>
</main>