<main id="equipes">
    <header>
        <h1>Séniors</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Séniors</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <a href="#">
                <article>
                    <header>
                        <h1></h1>
                    </header>
                    <figure>
                        <img src="/usdomagne/usdomagne/uploads/test_image_will.png" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="#">
                <article>
                    <header>
                        <h1></h1>
                    </header>
                    <figure>
                        <img src="/usdomagne/usdomagne/uploads/2.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="#">
                <article>
                    <header>
                        <h1></h1>
                    </header>
                    <figure>
                        <img src="/usdomagne/usdomagne/uploads/3.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="#">
                <article>
                    <header>
                        <h1></h1>
                    </header>
                    <figure>
                        <img src="/usdomagne/usdomagne/uploads/4.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
            <a href="#">
                <article>
                    <header>
                        <h1></h1>
                    </header>
                    <figure>
                        <img src="/usdomagne/usdomagne/uploads/5.jpg" alt="Image de l'équipe">
                    </figure>
                </article>
            </a>
        </section>
    </section>
</main>