<main>
    <section>
        <h1>Voir cet article :</h1>
        <!-- <?= var_dump($data['posts']); ?> -->
        <form> 
            <fieldset class="form-floating mb-3">
                <label for="show-title">Titre</label>
                <input type="text" class="form-control" name="show-title"  value="<?= $data['posts']->getTitle(); ?>" disabled="disabled">
            </fieldset>
            <fieldset class="form-floating mb-3">
                <label for="show-date">Date</label>
                <input type="date" class="form-control" name="show-date" value="<?= $data['posts']->getDate(); ?>" disabled="disabled">
            </fieldset>
            <fieldset class="form-floating mb-3">
                <label for="show-content">Texte</label>
                <textarea class="form-control" name="show-content" rows="10" cols="66" disabled="disabled"><?= $data['posts']->getContent(); ?></textarea>
            </fieldset>
            <fieldset class="form-floating mb-3">
                <figure>
                    <img src="/res03-projet-final/usdomagne/<?= $data['posts']->getMedias()[0]->getUrl(); ?>" alt="Image de l'article côté admin">
                </figure>
            </fieldset>
            <input type="hidden" name="formShowPost"/>
        </form>
    </section>
    <section class="section-btn">
        <button><a href="/res03-projet-final/usdomagne/admin/articles" class="btn btn-warning">Retour aux articles</a></button>
    </section>
</main>