<section id="login">
    <h1 class="sr-only">Se connecter à l'espace administrateur</h1>
    <form action="index.php?route=login" method="post">
        <h2>Se connecter à l'espace administrateur</h2>
        <fieldset>
            <label for="email">Email</label>
            <input type="email" name="email" />
        </fieldset>
        <fieldset>
            <label for="password">Mot de passe</label>
            <input type="password" name="password"/>
        </fieldset>
        <fieldset>
            <input type="submit" name="submit" value="Se connecter" id="login-button" />
        </fieldset>
        <input type="hidden" name="formRegister"/>
    </form>
</section>