<main id="admin-login">
        <h1>Se connecter à l'espace administrateur</h1>
        <form action="/usdomagne/usdomagne/admin" method="post" id="login-form">
            <fieldset class="form-floating mb-3">
                <label for="floatingInput">Email</label>
                <input type="email" id="email-login" class="form-control" id="floatingInput" name="email" />
            </fieldset>
            <fieldset class="form-floating">
                <label for="floatingPassword">Mot de passe</label>
                <input type="password" id="password-login" class="form-control" id="floatingPassword" name="password"/>
            </fieldset>
            <fieldset id="login-button">
                <input type="submit" class="btn btn-primary" name="submit" value="Se connecter" />
            </fieldset>
            <input type="hidden" name="formName" value = "login" />
        </form>
</main>