<header id="client-header-mobile">
    <section>
        <h2 class="sr-only">Bouton hamburger</h2>
        <button class="sideMenuMobile-btn">
            <span class="line l1"></span>
            <span class="line l2"></span>
            <span class="line l3"></span>
        </button>
        <figure>
            <a href="/res03-projet-final/usdomagne"><img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="logo"></a>
            <h1>US Domagné St-Didier</h1>
        </figure>
    </section>
    <nav class="sideMenuMobile">
        <ul>
            <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
            <li><a href="/res03-projet-final/usdomagne/actualites">Actualités</a></li>
            <li class="items-mobile"><a href="#">Équipes</a>
                <span class="fa-solid fa-chevron-right" style="color: #034076"></span>
                <ul class="submenu-headerMobile">
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/ecole-de-foot">École de foot</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/groupement-jeunes">Groupement Jeunes</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/veterans">Vétérans</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/seniors">Séniors</a></li>
                </ul>
            </li>
            <li class="items-mobile"><a href="#">Club</a>
                <span class="fa-solid fa-chevron-right" style="color: #034076"></span>
                <ul class="submenu-headerMobile">
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/histoire">L'histoire de l'USD</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/bureau">Le bureau</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/staff">Staff</a></li>
                    <li class="items-submenu-headerMobile"><a href="/res03-projet-final/usdomagne/infrastructures">Infrastructures</a></li>
                </ul>
            </li>
            <li><a href="/res03-projet-final/usdomagne/boutique">Boutique</a></li>
            <li><a href="/res03-projet-final/usdomagne/arbitres">Arbitrage</a></li>
            <li><a href="/res03-projet-final/usdomagne/convocations">Convocations</a></li>
            <li><a href="/res03-projet-final/usdomagne/partenaires">Partenaires</a></li>
            <li><a href="/res03-projet-final/usdomagne/albums">Albums</a></li>
            <li><a href="/res03-projet-final/usdomagne/contact">Contact</a></li>
        </ul>
        <section>
            <h2 class="sr-only">Barre de naviguation pour portable</h2>
            <ul class="socialIcons-SideMenuMobile">
                <li><a href="https://fr-fr.facebook.com/usdomagne/" class="icon-facebook" target="_blank"><span class="fab fa-facebook-f fa-lg"></span></a></li>
                <li><a href="https://www.instagram.com/usdomagne/?hl=fr" class="icon-instagram" target="_blank"><span class="fab fa-instagram fa-lg"></span></a></li>
                <li><a href="https://twitter.com/usdomagne" class="icon-twitter" target="_blank"><span class="fab fa-twitter fa-lg"></span></a></li>
            </ul>
        </section>
    </nav>
</header>