<header>
    <section>
        <h1 class="sr-only">Nos réseaux sociaux</h1>
        <p>Nos réseaux sociaux :</p>
        <ul>
            <li><a href="https://fr-fr.facebook.com/usdomagne/"><span class="fab fa-facebook-f"></span></a></li>
            <li><a href="https://www.instagram.com/usdomagne/?hl=fr"><span class="fab fa-instagram"></span></a></li>
            <li><a href="https://twitter.com/usdomagne"><span class="fab fa-twitter"></span></a></li>
        </ul>
    </section>
    <nav>
        <ul>
            <li><a href="">Menu</a>
                <ul class="sr-only">
                    <li>Le club
                        <ul>
                            <li>L'histoire de l'USD</li>
                            <li>Le bureau</li>
                            <li>Staff</li>
                            <li>Infrastructures</li>
                        </ul>
                    </li>
                    <li>Convocations</li>
                    <li>Partenaires</li>
                    <li>Albums</li>
                    <li>Contact</li>
                </ul>
            </li>
            <li><a href="">Accueil</a></li>
            <li><a href="">Actualités</a></li>
        </ul>
        <figure>
            <a href=""><img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="logo"></a>
            <p>Depuis 1962</p>
        </figure>
        <ul>
            <li><a href="">Équipes</a>
                <ul class="sr-only">
                    <li>École de foot</li>
                    <li>Groupement Jeunes</li>
                    <li>Vétérans</li>
                    <li>Séniors</li>
                </ul>
            </li>
            <li><a href="">Arbitres</a></li>
            <li><a href="">Boutique</a></li>
        </ul>
    </nav>
</header>