<header id="client-header">
    <aside class="sideMenu">
        <nav class="sideMenu-nav">
            <ul>
                <li><a href="/res03-projet-final/usdomagne/arbitres">Arbitrage</a></li>
                <li><a href="/res03-projet-final/usdomagne/convocations">Convocations</a></li>
                <li><a href="/res03-projet-final/usdomagne/partenaires">Partenaires</a></li>
                <li><a href="#">Albums</a></li>
                <li><a href="/res03-projet-final/usdomagne/contact">Contact</a></li>
            </ul>
        </nav>
    </aside>
    <section>
        <h1><a href="/res03-projet-final/usdomagne/admin"><span class="fa-regular fa-user"></span>Espace administrateur</a></h1>
        <ul>
            <li>Nos réseaux sociaux :</li>
            <li><a href="https://fr-fr.facebook.com/usdomagne/" class="icon-facebook"><span class="fab fa-facebook-f fa-lg"></span></a></li>
            <li><a href="https://www.instagram.com/usdomagne/?hl=fr" class="icon-instagram"><span class="fab fa-instagram fa-lg"></span></a></li>
            <li><a href="https://twitter.com/usdomagne" class="icon-twitter"><span class="fab fa-twitter fa-lg"></span></a></li>
        </ul>
    </section>
    <nav>
        <button class="sideMenu-btn">
            <span class="line l1"></span>
            <span class="line l2"></span>
            <span class="line l3"></span>
        </button>
        <ul>
            <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
            <li><a href="/res03-projet-final/usdomagne/actualites">Actualités</a></li>
        </ul>
        <figure>
            <a href="/res03-projet-final/usdomagne"><img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="logo"></a>
        </figure>
        <ul>
            <li class="items"><a href="/res03-projet-final/usdomagne/equipes">Équipes</a>
                <span class="fa-solid fa-chevron-down fa-lg" style="color: #034076"></span>
                <ul class="submenu-headerLaptop">
                    <li class="items-submenu-headerLaptop"><a href="#">École de foot</a></li>
                    <li class="items-submenu-headerLaptop"><a href="#">Groupement Jeunes</a></li>
                    <li class="items-submenu-headerLaptop"><a href="#">Vétérans</a></li>
                    <li class="items-submenu-headerLaptop"><a href="#">Séniors</a></li>
                </ul>
            </li>
            <li class="items"><a href="/res03-projet-final/usdomagne/club">Club</a>
                <span class="fa-solid fa-chevron-down fa-lg" style="color: #034076"></span>
                <ul class="submenu-headerLaptop">
                    <li class="items-submenu-headerLaptop"><a href="/res03-projet-final/usdomagne/histoire">L'histoire de l'USD</a></li>
                    <li class="items-submenu-headerLaptop"><a href="#">Le bureau</a></li>
                    <li class="items-submenu-headerLaptop"><a href="#">Staff</a></li>
                    <li class="items-submenu-headerLaptop"><a href="/res03-projet-final/usdomagne/infrastructures">Infrastructures</a></li>
                </ul>
            </li>
            <li class="items"><a href="/res03-projet-final/usdomagne/boutique">Boutique</a></li>
        </ul>
    </nav>
</header>