<header id="client-header-mobile">
    <nav>
        <ul>
            <li><span class="fa-solid fa-bars fa-2xl" style="color: #ffffff;"></span>
                <ul class="sr-only">
                    <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                    <li><a href="/res03-projet-final/usdomagne/actualites">Actualités</a></li>
                    <li><a href="/res03-projet-final/usdomagne/equipes">Équipes</a>
                        <ul class="sr-only">
                            <li><a href="">École de foot</a></li>
                            <li><a href="">Groupement Jeunes</a></li>
                            <li><a href="">Vétérans</a></li>
                            <li><a href="">Séniors</a></li>
                        </ul>
                    </li>
                    <li><a href="/res03-projet-final/usdomagne/club">Club</a>
                        <ul class="sr-only">
                            <li><a href="/res03-projet-final/usdomagne/histoire">L'histoire de l'USD</a></li>
                            <li><a href="">Le bureau</a></li>
                            <li><a href="">Staff</a></li>
                            <li><a href="/res03-projet-final/usdomagne/infrastructures">Infrastructures</a></li>
                        </ul>
                    </li>
                    <li><a href="/res03-projet-final/usdomagne/boutique">Boutique</a></li>
                    <li><a href="/res03-projet-final/usdomagne/arbitres">Arbitrage</a></li>
                    <li><a href="/res03-projet-final/usdomagne/convocations">Convocations</a></li>
                    <li><a href="/res03-projet-final/usdomagne/partenaires">Partenaires</a></li>
                    <li><a href="/res03-projet-final/usdomagne/albums">Albums</a></li>
                    <li><a href="/res03-projet-final/usdomagne/contact">Contact</a></li>
                    <li>
                        <section>
                            <h1 class="sr-only">Barre de naviguation pour portable</h1>
                            <ul>
                                <li><a href="https://fr-fr.facebook.com/usdomagne/" class="icon-facebook"><span class="fab fa-facebook-f fa-lg"></span></a></li>
                                <li><a href="https://www.instagram.com/usdomagne/?hl=fr" class="icon-instagram"><span class="fab fa-instagram fa-lg"></span></a></li>
                                <li><a href="https://twitter.com/usdomagne" class="icon-twitter"><span class="fab fa-twitter fa-lg"></span></a></li>
                            </ul>
                        </section>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <section>
        <figure>
                <a href="/res03-projet-final/usdomagne"><img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="logo"></a>
                <h1>US Domagné St-Didier</h1>
        </figure>
    </section>
</header>