<header id="admin-header">
    <h1>Administrateur</h1>
    <ul>
        <?php 
        /*var_dump($_SESSION);*/
        
        if(isset($_SESSION) && isset( $_SESSION['isConnected'])  && $_SESSION['isConnected'] === true)
        { 
            
            echo "<li>".$_SESSION['username']."</li>"; 
            
            echo "<li><a href='/usdomagne/usdomagne/logout'>Déconnexion</a></li>";
        }; 
        
        ?>
    </ul>
</header>