<footer id="footer-client">
    <figure>
        <img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="Logo du club dans le footer">
    </figure>
    <section>
        <section>
            <h1>US Domagné</h1>
            <ul>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
            </ul>
        </section>
        <section>
            <h1>Services</h1>
            <ul>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
            </ul>
        </section>
        <section>
            <h1>Nous suivre</h1>
            <ul>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
                <li><a href="#">lorem ipsum</a></li>
            </ul>
        </section>
    </section>
</footer>