<footer id="footer-client">
    <figure>
        <img src="https://s3.static-footeo.com/100/uploads/us-domagnestdidier/logo__75nixo4eg.png" alt="Logo du club dans le footer">
    </figure>
    <section>
        <section>
            <h1>US Domagné</h1>
            <ul>
                <li><a href="#">Les équipes</a></li>
                <li><a href="#">Le bureau</a></li>
                <li><a href="#">L'histoire de l'USD</a></li>
            </ul>
        </section>
        <section>
            <h1>Services</h1>
            <ul>
                <li><a href="#">Nous contacter</a></li>
                <li><a href="#">Cookies</a></li>
                <li><a href="#">Mentions légales</a></li>
            </ul>
        </section>
        <section>
            <h1>Nous suivre</h1>
            <ul>
                <li><a href="https://fr-fr.facebook.com/usdomagne/" class="icon-facebook" target="_blank"><span class="fa-brands fa-square-facebook fa-2xl"></span></a></li>
                <li><a href="https://www.instagram.com/usdomagne/?hl=fr" class="icon-instagram" target="_blank"><span class="fa-brands fa-square-instagram fa-2xl"></span></a></li>
                <li><a href="https://twitter.com/usdomagne" class="icon-twitter" target="_blank"><span class="fa-brands fa-square-x-twitter fa-2xl"></span></a></li>
            </ul>
        </section>
    </section>
</footer>