<main id="infrastructures">
    <header>
        <h1>Infrastructures</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Infrastructures</li>
            </ul>
        </nav>
    </header>
    <section>
        <h2>Nos terrains</h2>
    </section>
    <section>
        <section>
            <article>
                <figure>
                    <img src="https://s3.static-footeo.com/1200/uploads/us-domagnestdidier/grounds/dsc_0480__o8nh0i.jpg" alt="Image terrain d'honneur">
                </figure>
                <section>
                    <h3>Terrain d'Honneur</h3>
                </section>
            </article>
            <article>
                <figure>
                    <img src="https://s2.static-footeo.com/1200/uploads/us-domagnestdidier/grounds/dsc_0467__o8nh7v.jpg" alt="Image terrain d'entrainement">
                </figure>
                <section>
                    <h3>Terrain d'entrainement</h3>
                </section>
            </article>
        </section>
    </section>
</main>