<main id="staff">
    <header>
        <h1>Staff</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Staff</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach($data['pageStaff'] as $staff){ ?> 
            <article>
                <figure>
                    <img src="/usdomagne/usdomagne/<?= $staff->getMedias()[0]->getUrl(); ?>" alt="Image du staff">
                </figure>
                <section>
                    <h2><?= $staff->getFirstName(); ?><span> </span><?= $staff->getlastName(); ?></h2>
                    <h3><?= $staff->getRole(); ?></h3>
                </section>
            </article>
            <?php } ?>
        </section>
    </section>
</main>