<main id="staff">
    <header>
        <h1>Staff</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Staff</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach ($data['pageStaff'] as $staff) { ?>

                <figure>
                    <img src="/usdomagne/usdomagne/<?= $staff->getMedias()[0]->getUrl(); ?>" alt="Image du staff">
                </figure>


            <?php } ?>
        </section>
    </section>
</main>