<main id="homepage">
    <header>
        <h1 class="sr-only">Photo de la page d'accueil</h1>
        <figure>
            <img src="./assets/images/homepage_background.jpg" alt="Photo de l'USD saison 2022-2023">
        </figure>
    </header>
    <section>
        <h2>Prochains matchs de nos séniors :</h2>
        <article>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
            <script>
                if (!window._rsz) {
                    window._rsz = function() {
                        var i = iFrameResize({
                            checkOrigin: false,
                            interval: 100
                        });
                    };
                    if (document.readyState != "loading") {
                        _rsz()
                    } else {
                        document.addEventListener("DOMContentLoaded", _rsz)
                    }
                }
            </script><iframe id="643673b83712f009c955bca2" src="https://scorenco.com/widget/643673b83712f009c955bca2/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;"></iframe>
        </article>
    </section>
    <section>
        <section id="homepage-carousel">
            <h2 class="sr-only">Section avec un caroussel des actualités</h2>
            <section class="mainSlider_nav">
                <ul>
                    <li class="mainSlider_btn mainSlider_btn_prev"><i class="fa-solid fa-circle-chevron-left fa-2xl"></i></li>
                    <li class="mainSlider_btn mainSlider_btn_next"><i class="fa-solid fa-circle-chevron-right fa-2xl"></i></li>
                </ul>
            </section>
            <section class="mainSlider">
                <?php foreach ($data['homepagePosts'] as $post) { ?>
                    <article class="mainSlider_content active">
                        <h2 class="sr-only">Actualité du caroussel</h2>
                        <figure class="mainSlider_content_item">
                            <img src="/res03-projet-final/usdomagne/<?= $post->getMedias()[0]->getUrl(); ?>" alt="Image de l'actualité principale de la page d'accueil">
                        </figure>
                        <footer>
                            <h3><a href="/res03-projet-final/usdomagne/actualites/actu/<?= $post->getId(); ?>"><?= $post->getTitle(); ?></a></h3>
                        </footer>
                    </article>
                <?php } ?>
            </section>
            <aside>
                <header>
                    <h2>Dernières minutes</h2>
                </header>
                <?php foreach ($data['homepagePosts'] as $post) { ?>
                    <article>
                        <h2 class="sr-only">Article dans la section "Dernières minutes"</h2>
                        <span><?= $post->getDate(); ?></span>
                        <p><?= $post->getTitle(); ?></p>
                    </article>
                <?php } ?>
            </aside>
        </section>
    </section>
    <section>
        <section id="homepage-actualites">
            <h2 class="sr-only">Section avec les trois dernières actualités</h2>
            <section>
                <h2 class="sr-only">Section dans la section avec les trois dernières actualités"</h2>
                <header>
                    <h2>Actualités</h2>
                </header>
                <?php
                foreach ($data['homepagePosts'] as $post) { ?>
                    <article>
                        <h2 class="sr-only">Un des trois derniers articles</h2>
                        <a href="/res03-projet-final/usdomagne/actualites/actu/<?= $post->getId(); ?>">
                            <figure>
                                <img src="/res03-projet-final/usdomagne/<?= $post->getMedias()[0]->getUrl(); ?>" alt="Image de l'actu">
                            </figure>
                        </a>
                        <section>
                            <h2 class="sr-only">Section de l'article</h2>
                            <header>
                                <a href="/res03-projet-final/usdomagne/actualites">Actualités</a>
                                <span><?= $post->getDate(); ?></span>
                            </header>
                            <h3><a href="/res03-projet-final/usdomagne/actualites/actu/<?= $post->getId(); ?>"><?= $post->getTitle(); ?></a></h3>
                            <p><?= $post->getContent(); ?></p>
                        </section>
                    </article>
                <?php } ?>
            </section>
            <aside>
                <header>
                    <h2>Classement</h2>
                </header>
                <iframe id="643ea8e891d359679f19a24e" height="300" src="https://v1.scorenco.com/widget/643ea8e891d359679f19a24e/" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;"></iframe>
            </aside>
        </section>
    </section>
    <section>
        <h2 class="sr-only">Section partenaires</h2>
        <section id="partenaires">
            <h2 class="sr-only">Section partenaires</h2>
            <header>
                <h2>Nos partenaires</h2>
            </header>
            <section class="slider_section_btn">
                <button class="slider_btn slider_btn_prev" class="fa-solid fa-circle-chevron-left fa-2xl">Précédent</button>
                <button class="slider_btn slider_btn_next" class="fa-solid fa-circle-chevron-right fa-2xl">Suivant</button>
            </section>
            <section class="slider_content">
                <figure class="slider_content_item">
                    <img src="https://s1.static-footeo.com/uploads/us-domagnestdidier/sponsors/8-a-huit__qbhyhp.jpg" alt="Image du partenaire">
                </figure>
                <figure class="slider_content_item">
                    <img src="https://s3.static-footeo.com/uploads/us-domagnestdidier/sponsors/ajus-tifs__qbhyf6.png" alt="Image du partenaire">
                </figure>
                <figure class="slider_content_item">
                    <img src="https://s3.static-footeo.com/uploads/us-domagnestdidier/sponsors/874064befd17df3f7ab95399bf80114ec220f371__ojeyb8.jpg" alt="Image du partenaire">
                </figure>
                <figure class="slider_content_item">
                    <img src="https://s2.static-footeo.com/uploads/us-domagnestdidier/sponsors/b3a48b6328f10d51f482ae10299abee7413b3d37__qbhyi2.jpg" alt="Image du partenaire">
                </figure>
                <figure class="slider_content_item">
                    <img src="https://s1.static-footeo.com/uploads/us-domagnestdidier/sponsors/3d04fdd38d93787fb4d8e8db3382e6cd6851dc67__ojeyqn.jpg" alt="Image du partenaire">
                </figure>
                <figure class="slider_content_item">
                    <img src="https://s1.static-footeo.com/uploads/us-domagnestdidier/sponsors/f47837c86fb17fd20505826acff4f21ce2ca5024__ojeyqy.jpg" alt="Image du partenaire">
                </figure>
            </section>
        </section>
    </section>
</main>