<main id="homepage">
    <header>
        <h1 class="sr-only">Photo de la page d'accueil</h1>
        <figure>
            <img src="./assets/images/homepage_background.jpg" alt="Photo de l'USD saison 2022-2023">
        </figure>
    </header>
    <section>
        <h2>Prochains matchs de nos séniors :</h2>
        <article>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script><script>if(!window._rsz){window._rsz=function(){var i=iFrameResize({checkOrigin:false,interval:100});};if(document.readyState!="loading"){_rsz()}else{document.addEventListener("DOMContentLoaded",_rsz)}}</script><iframe id="643673b83712f009c955bca2" src="https://scorenco.com/widget/643673b83712f009c955bca2/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
        </article>
    </section>
    <section>
        <section id="homepage-carousel">
            <article>
                <figure>
                    <img src="https://s3.static-footeo.com/750/uploads/us-domagnestdidier/news/neon-blue-flash-sale-facebook-post-1-1__rsmv5y.png">
                </figure>
                <footer>
                    <h3>Destockage !!!</h3>
                </footer>
            </article>
            <aside>
                <header>
                    <h2>Dernières minutes</h2>
                </header>
                <article>
                    <h3>Destockage !!!</h3>
                    <p>Chaussettes et shorts en réduction</p>
                </article>
            </aside>
        </section>
    </section>
    <section>
        <section id="homepage-actualites">
            <article>
                <figure>
                    <img src="#">
                </figure>
                <section>
                    <header>
                        <button><span>Actualités</span></button>
                        <p>Il y a 1 jour</p>
                    </header>
                    <h1>Première actualité</h1>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </section>
            </article>
            <aside>
                <header>
                    <h1>Classement</h1>
                </header>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script><script>if(!window._rsz){window._rsz=function(){var i=iFrameResize({checkOrigin:false,interval:100});};if(document.readyState!="loading"){_rsz()}else{document.addEventListener("DOMContentLoaded",_rsz)}}</script><iframe id="643ea8e891d359679f19a24e" src="https://scorenco.com/widget/643ea8e891d359679f19a24e/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
            </aside>
        </section>
    </section>
    <section>
        <section id="partenaires">
            
        </section>
    </section>
</main>


