<main>
    <section>
        <h1 class="sr-only">Photo de la page d'accueil</h1>
        <figure>
            <img src="./assets/images/homepage_background.jpg" alt="Photo de l'USD saison 2022-2023">
        </figure>
    </section>
    <section>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
        <script>if(!window._rsz){window._rsz=function(){var i=iFrameResize({checkOrigin:false,interval:100});};if(document.readyState!="loading"){_rsz()}else{document.addEventListener("DOMContentLoaded",_rsz)}}</script>
        <iframe id="641586784a9f716346d06fd7" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
        <script type="text/javascript">var u=["https:","","/scorenco.com","widget","641586784a9f716346d06fd7",""];document.getElementById("641586784a9f716346d06fd7").src=u.join("/");</script>
        <a href="https://scorenco.com/football/clubs/us-domagne-st-didier/">US Domagné St Didier sur Score'n'co</a>
    </section>
    <section>
        <article>
            
        </article>
        <aside>
            
        </aside>
    </section>
</main>


