<main id="partenaires">
    <header>
        <h1>Partenaires</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Partenaires</li>
            </ul>
        </nav>
    </header>
    <section>
        <figure>
            <img src="assets/images/CAFPI.png" alt="Image du partenaire">
        </figure>
        <figure>
            <img src="assets/images/CAPCLIMAT.png" alt="Image du partenaire">
        </figure>
        <figure>
            <img src="assets/images/CLOUET.png" alt="Image du partenaire">
        </figure>
        <figure>
            <img src="assets/images/FERRON.png" alt="Image du partenaire">
        </figure>
        <figure>
            <img src="assets/images/PLANCHAIS.png" alt="Image du partenaire">
        </figure>
        <figure>
            <img src="assets/images/VAND.png" alt="Image du partenaire">
        </figure>
    </section>
</main>