<main id="actualites">
    <header>
        <h1>Actualités</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Actualités</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach ($data['pageActualites'] as $actu) { ?>
                <article>
                    <a href="/usdomagne/usdomagne/actualites/actu/<?= $actu->getId(); ?>">
                        <figure>
                            <img src="/usdomagne/usdomagne/<?= $actu->getMedias()[0]->getUrl(); ?>" alt="Image de l'actualité">
                        </figure>
                    </a>
                    <header>
                        <a href="/usdomagne/usdomagne/actualites">Actualités</a>
                        <span><?= $actu->getDate(); ?></span>
                    </header>
                    <h3><a href="/usdomagne/usdomagne/actualites/actu/<?= $actu->getId(); ?>"><?= $actu->getTitle(); ?></a></h3>
                    <p><?= $actu->getContent(); ?></p>
                </article>
            <?php } ?>
        </section>
    </section>
</main>