<main id="actu">
    <header>
        <h1>Actu</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li><a href="/usdomagne/usdomagne/actualites">Actualités</a></li>
                <li><span>/</span></li>
                <li>Actu</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach($data['actus'] as $actu){ ?> 
            <figure>
                <img src="/usdomagne/usdomagne/<?= $actu->getMedias()[0]->getUrl(); ?>" alt="Image de l'actu">
            </figure>
            <section>
                <header>
                    <h2><?= $actu->getTitle(); ?></h2>
                </header>
                <p><?= $actu->getContent(); ?></p>
                <span><?= $actu->getDate(); ?></span>
            </section>
            <?php } ?>
        </section>
    </section>
</main>