<main id="actualites">
    <header>
        <h1>Actualités</h1>
        <nav>
            <ul>
                <li><a href="/res03-projet-final/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Actualités</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <?php foreach($data['pageActualites'] as $actu){ ?> 
            <article>
                <figure>
                    <img src="/res03-projet-final/usdomagne/<?= $actu->getMedias()[0]->getUrl(); ?>" alt="Image de l'actualité">
                </figure>
                <header>
                    <a href="/res03-projet-final/usdomagne/actualites">Actualités</a>
                    <span><?= $actu->getDate(); ?></span>
                </header>
                <h3><?= $actu->getTitle(); ?></h3>
                <p><?= $actu->getContent(); ?></p>
            </article>
            <?php } ?>
        </section>
    </section>
</main>