<section id="register">
    <h1 class="sr-only">Créer un admin</h1>
    <form method="post" action="index.php?route=register">
        <h2>Créer un admin</h2>
        <fieldset>
            <label for="admin-firstname">Prénom</label>
            <input type="text" name="admin-name" />
        </fieldset>
        <fieldset>
            <label for="admin-lastname">Nom</label>
            <input type="text" name="admin-firstname" />
        </fieldset>
        <fieldset>
            <label for="admin-email">Email</label>
            <input type="email" name="admin-email" />
        </fieldset>
        <fieldset>
            <label for="admin-password">Mot de passe</label>
            <input type="password" name="admin-password" />
        </fieldset>
        <fieldset>
            <label for="admin-confirm-pwd">Confirmer le mot de passe</label>
            <input type="password" name="confirm-pwd"/>
        </fieldset>
        <fieldset>
            <input type="submit" name="submit" value="S'enregistrer" id="register-button" />
        </fieldset>
        <input type="hidden" name="formRegister"/>
    </form>
</section>