<form action="/res03-projet-final/usdomagne/admin/media/creer-un-media" method="post">
    <fieldset>
        <label for="add-url">Url</label>
        <input type="file" name="add-url"/>
    </fieldset>
    <fieldset>
        <label for="add-caption">Caption</label>
        <input type="text" name="add-caption"/>
    </fieldset>
    <fieldset>
        <label for="add-relation">Relation</label>
        <input type="text" name="add-relation"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer" />
    </fieldset>
    <input type="hidden" name="formAddMedia"/>
</form>
<button><a href="/res03-projet-final/usdomagne/admin/media">Retour aux medias</a></button>