<form action="/usdomagne/usdomagne/admin/media/creer-un-media" method="post" enctype="multipart/form-data">
    <fieldset>
        <label for="add-image">Image</label>
        <input type="file" name="add-image"/>
    </fieldset>
    <fieldset>
        <label for="add-caption">Description</label>
        <input type="text" name="add-caption"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Enregistrer" />
    </fieldset>
    <input type="hidden" name="formAddMedia"/>
</form>
<button><a href="/usdomagne/usdomagne/admin/media">Retour aux medias</a></button>