<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($data['media'] as $media){ ?>
        
        <tr>
            <td><?php echo $media->getId(); ?></td>
            <td><?php echo $media->getName(); ?></td>
            <td><?php echo $media->getUrl(); ?></td>
            <td>
                <a href="/res03-projet-final/usdomagne/admin/media/supprimer/<?= $media->getId(); ?>">Supprimer</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<button><a href="/res03-projet-final/usdomagne/admin">Retour au menu</a></button>