<main id="boutique">
    <header>
        <h1>Boutique</h1>
    </header>
    <section>
        <figure>
            <img src="assets/images/Boutique.png" alt="Qr code de la boutique de l'US Domagné">
        </figure>
        <section>
            <a href="https://b6.intersport-boutique-club.fr/500-us-domagne-saint-didier" target=”_blank”>
                <section>
                    <h2>Cliquez ici</h2>
                    <h3><i class="fa-solid fa-basket-shopping fa-2xl"></i></h3>
                </section>
            </a>
        </section>
    </section>
</main>