<main id="convocations">
    <header>
        <h1>Convocations</h1>
        <nav>
            <ul>
                <li><a href="/usdomagne/usdomagne">Accueil</a></li>
                <li><span>/</span></li>
                <li>Convocations</li>
            </ul>
        </nav>
    </header>
    <section>
        <section>
            <h2>Pôle séniors & vétérans</h2>
            <nav>
                <ul>
                    <a href="usdomagne/usdomagne/convocations/convocations-seniors"><li>Séniors D2 D3 D4</li></a>
                    <a href="usdomagne/usdomagne/convocations/convocations-veterans"><li>Vétérans</li></a>
                </ul>
            </nav>
        </section>
        <section>
            <h2>Pôle jeunes</h2>
            <nav>
                <ul>
                    <a href="usdomagne/usdomagne/convocations/convocations-u17"><li>Jeunes U17</li></a>
                    <a href="usdomagne/usdomagne/convocations/convocations-u15"><li>Jeunes U15</li></a>
                    <a href="usdomagne/usdomagne/convocations/convocations-u13"><li>Jeunes U13</li></a>
                </ul>
            </nav>
        </section>
    </section>
</main>